theme = "papercolor-light"

[editor]
auto-pairs = false
line-number = "relative"
gutters = ["diagnostics", "line-numbers", "spacer"]
true-color = true
shell = ["fish", "-i",  "-c"]

[editor.statusline]
center = ["mode", "spinner", "diagnostics"]
left = ["file-name", "file-type", "file-encoding"]
right = ["selections", "file-line-ending", "position"]
separator = "|"

[editor.whitespace]
render = "all"

[editor.lsp]
display-messages = true

[keys.normal]
"!" = "shell_append_output"
"A-!" = "shell_insert_output"
