
[[language]]
name = "python"
auto-format = true
diagnostic-severity = "Hint"
indent = { tab-width = 4, unit = "  " }

[[language]]
name = "nix"
auto-format = true
indent = { tab-width = 4, unit = "  "  }
formatter = { command = "nixfmt" }
